### ISSUE TITLE
index.js not found, how to upload LambCI package?

### ISSUE THREAD

**Issue by sgluss** [lambci/lambci#100]
while tinkering with LambCI trying to configure a package with added binaries, I noticed that builds were no longer triggering. I checked the LambCI logs and found this error:

```
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/utils/log.js:4:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
```

so I tried zipping the contents of the lambCI repo (index.js is at the root of the archive), and re-uploaded that as the function code (configured to use Node 6.10)

I still get the error, is this not the right way to load the stock LambCI package?

(I'm trying to use lambCI to build and deploy a Hugo Site, I have been trying to work out how to package additional binary executables such as Hugo as well)

**Comment by sgluss** [comment]
figured it out.

1. clone lambci repo
2. run `npm install` in repo root [see aws docs](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html)
3. zip repo (index.js should be at the top level of the zip file)
4. upload the zip file as the function package in the AWS lambda function config
