### ISSUE TITLE
Failed DynamoDB update when committer is unexpected

### ISSUE THREAD

**Issue by mhaji** [lambci/lambci#23]
I've set up a [simple project](https://github.com/mhaji/lamb-ci-test) to try out LambCI, essentially a barebones copy of [mhart/test-ci-project](https://github.com/mhart/test-ci-project).

The first build triggered successfully and I could view the logs in CloudWatch, albeit it was a failed build (expected) due to not finding the package.json as the project only had a README.md at the time. You can see the output of that [here](https://s3.amazonaws.com/lambci-demo-buildresults-5bud2r550kww/gh/mhaji/lamb-ci-test/builds/1/c845d962e0754095f8a58de1b6bd87dc.html).

I then copied some of [mhart/test-ci-project](https://github.com/mhart/test-ci-project) to add a simple NodeJS test, committed and pushed. I was presented with this stacktrace in CloudWatch:

	2016-07-10T16:12:16.221Z	9a1541fb-46b8-11e6-bf88-f9860b5e257a	InvalidSetType: Sets can contain string, number, or binary values
	 at Set.util.inherit.detectType (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:30:24)
	 at Set.util.inherit.initialize (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:14:10) 
	 at new Set (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:8:10) 
	 at DocumentClient.AWS.DynamoDB.DocumentClient.AWS.util.inherit.createSet (/var/runtime/node_modules/aws-sdk/lib/dynamodb/document_client.js:451:12) 
	 at /var/task/db/index.js:107:60 
	 at Response.<anonymous> (/var/task/db/index.js:65:5) 
	 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:355:18) 
	 at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20) 
	 at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:615:14)

This points to line [107 in db/injex.js](https://github.com/lambci/lambci/blob/master/db/index.js#L107). 

So I think what's happened is this: 

My local git config `user.email` property was set to a corporate email address and not one that is linked to my Github account (obviously my fault). My [commit history](https://github.com/mhaji/lamb-ci-test/commits/master) shows that.

Updating the `user.email` property locally and committing again fixed the issue.

To reproduce this:

1. Set up project and integrate with LambCI
2. Ensure builds are being triggered in response to commits
3. Update your git config `user.email` property to an email not linked to your Github account: `git config user.email "$UNRECOGNISED_AUTHOR"`
4. `git commit --allow-empty -m 'Trigger another LambCI build' && git push`

**Comment by mhaji** [comment]
I've uploaded a new zip to Lambda with a log line added to `db/index.js` before `client.put`:

    log.info(build.committers)
    log.info(Array.from(build.committers))

This outputs:

    2016-07-10T17:33:11.816Z	5ca39eee-46c4-11e6-a459-41d3b5762327	Set { undefined } 
    2016-07-10T17:33:11.817Z	5ca39eee-46c4-11e6-a459-41d3b5762327	[ undefined ] 

this happens in the case where the committer's email is not linked to the user's Github account.

**Comment by mhart** [comment]
Great tracking down – yeah, I should make sure to get rid of any undefined elements, hadn't really considered that.

Thanks for reporting!

**Comment by mhart** [comment]
This is fixed in v0.9.2 – thanks again for reporting it!
