### ISSUE TITLE
Error: Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by franciscocpg** [lambci/lambci#89]
Any attempt to run `npm` at `cmd` is giving this error:
```
2017-08-16T13:36:55.400Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 $ npm -v
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 module.js:327
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 throw err;
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 ^
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 Error: Cannot find module 'npmlog'
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Function.Module._resolveFilename (module.js:325:15)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Function.Module._load (module.js:276:25)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Module.require (module.js:353:17)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at require (internal/module.js:12:17)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at /var/task/node_modules/.bin/npm:18:11
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Object.<anonymous> (/var/task/node_modules/.bin/npm:75:3)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Module._compile (module.js:409:26)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Object.Module._extensions..js (module.js:416:10)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Module.load (module.js:343:32)
2017-08-16T13:36:55.585Z f7cf8f1e-8287-11e7-8f34-cb6c22e923f3 at Function.Module._load (module.js:300:12)
```

**Comment by mhart** [comment]
Can't reproduce, looks fine for me:

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/167/585a8971fa5a757254757713ae2c6a87.html

That was a build of this commit:

https://github.com/mhart/test-ci-project/commit/da9b2f114a49d72dff81edc379577e01ffcec5df

**Comment by franciscocpg** [comment]
Hm, I don't know what is the root cause.
But I was able to workaround it by using `nave`. Eg `nave use 8 bash -c 'npm -v'`.
